#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH="/usr/local/nvim-linux64/bin":$PATH
export PATH="/usr/lib/llvm-11/bin":$PATH
# export PATH=$HOME/.fnm:$PATH
export PATH="$PATH:./node_modules/.bin"
export NEMU_HOME=/home/shives/courses/why-ICS/ics2023/nemu
export AM_HOME=/home/shives/courses/why-ICS/ics2023/abstract-machine

# eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

case ":${PATH}:" in
    *:"$HOME/.cargo/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$HOME/.cargo/bin:$PATH"
        ;;
esac

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/shives/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/shives/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/shives/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/shives/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

if [ $LD_LIBRARY_PATH ]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/wsl/lib
else
    export LD_LIBRARY_PATH=/usr/local/cuda/lib64
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/wsl/lib
fi
export PATH=$PATH:/usr/local/cuda/bin

if [ $CUDA_HOME ]; then
   export CUDA_HOME=$CUDA_HOME:/usr/local/cuda
else
   export CUDA_HOME=/usr/local/cuda
fi

