#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export PATH="/usr/local/nvim-linux64/bin":$PATH
export PATH="/usr/lib/llvm-11/bin":$PATH
export PATH="$PATH:./node_modules/.bin"
export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

export NEMU_HOME=/home/shives/courses/why-ICS/ics2023/nemu
export AM_HOME=/home/shives/courses/why-ICS/ics2023/abstract-machine


export MANPAGER="/bin/sh -c \"col -b | vim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""
export MANWIDTH=999 
eval "$(zoxide init zsh)"




if [ $LD_LIBRARY_PATH ]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/wsl/lib
else
    export LD_LIBRARY_PATH=/usr/local/cuda/lib64
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/wsl/lib
fi
export PATH=$PATH:/usr/local/cuda/bin

if [ $CUDA_HOME ]; then
   export CUDA_HOME=$CUDA_HOME:/usr/local/cuda
else
   export CUDA_HOME=/usr/local/cuda
fi


[ -f ~/.secrets ] && source ~/.secrets

case ":${PATH}:" in
    *:"$HOME/.cargo/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$HOME/.cargo/bin:$PATH"
        ;;
esac

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
